# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keyconfig.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_KeyConfig(object):
    def setupUi(self, KeyConfig):
        KeyConfig.setObjectName("KeyConfig")
        KeyConfig.resize(271, 302)
        self.widget_left = QtWidgets.QWidget(KeyConfig)
        self.widget_left.setGeometry(QtCore.QRect(9, 9, 124, 44))
        self.widget_left.setObjectName("widget_left")
        self.lineEdit_left = QtWidgets.QLineEdit(self.widget_left)
        self.lineEdit_left.setGeometry(QtCore.QRect(60, 10, 51, 21))
        self.lineEdit_left.setMinimumSize(QtCore.QSize(51, 21))
        self.lineEdit_left.setMaximumSize(QtCore.QSize(51, 21))
        self.lineEdit_left.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_left.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_left.setObjectName("lineEdit_left")
        self.label = QtWidgets.QLabel(self.widget_left)
        self.label.setGeometry(QtCore.QRect(10, 10, 43, 17))
        self.label.setMinimumSize(QtCore.QSize(43, 17))
        self.label.setMaximumSize(QtCore.QSize(43, 17))
        self.label.setObjectName("label")
        self.widget_right = QtWidgets.QWidget(KeyConfig)
        self.widget_right.setGeometry(QtCore.QRect(139, 9, 123, 44))
        self.widget_right.setObjectName("widget_right")
        self.lineEdit_right = QtWidgets.QLineEdit(self.widget_right)
        self.lineEdit_right.setGeometry(QtCore.QRect(60, 10, 51, 21))
        self.lineEdit_right.setMinimumSize(QtCore.QSize(51, 21))
        self.lineEdit_right.setMaximumSize(QtCore.QSize(51, 21))
        self.lineEdit_right.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_right.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_right.setObjectName("lineEdit_right")
        self.label_2 = QtWidgets.QLabel(self.widget_right)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 43, 17))
        self.label_2.setMinimumSize(QtCore.QSize(43, 17))
        self.label_2.setMaximumSize(QtCore.QSize(43, 17))
        self.label_2.setObjectName("label_2")
        self.widget_left_3 = QtWidgets.QWidget(KeyConfig)
        self.widget_left_3.setGeometry(QtCore.QRect(9, 59, 124, 44))
        self.widget_left_3.setObjectName("widget_left_3")
        self.lineEdit_left_3 = QtWidgets.QLineEdit(self.widget_left_3)
        self.lineEdit_left_3.setGeometry(QtCore.QRect(60, 10, 51, 21))
        self.lineEdit_left_3.setMinimumSize(QtCore.QSize(51, 21))
        self.lineEdit_left_3.setMaximumSize(QtCore.QSize(51, 21))
        self.lineEdit_left_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_left_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_left_3.setObjectName("lineEdit_left_3")
        self.label_3 = QtWidgets.QLabel(self.widget_left_3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 43, 17))
        self.label_3.setMinimumSize(QtCore.QSize(43, 17))
        self.label_3.setMaximumSize(QtCore.QSize(43, 17))
        self.label_3.setObjectName("label_3")
        self.widget_right_3 = QtWidgets.QWidget(KeyConfig)
        self.widget_right_3.setGeometry(QtCore.QRect(139, 59, 123, 44))
        self.widget_right_3.setObjectName("widget_right_3")
        self.lineEdit_right_3 = QtWidgets.QLineEdit(self.widget_right_3)
        self.lineEdit_right_3.setGeometry(QtCore.QRect(60, 10, 51, 21))
        self.lineEdit_right_3.setMinimumSize(QtCore.QSize(51, 21))
        self.lineEdit_right_3.setMaximumSize(QtCore.QSize(51, 21))
        self.lineEdit_right_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_right_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_right_3.setObjectName("lineEdit_right_3")
        self.label_4 = QtWidgets.QLabel(self.widget_right_3)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 43, 17))
        self.label_4.setMinimumSize(QtCore.QSize(43, 17))
        self.label_4.setMaximumSize(QtCore.QSize(43, 17))
        self.label_4.setObjectName("label_4")
        self.widget_left_direct = QtWidgets.QWidget(KeyConfig)
        self.widget_left_direct.setGeometry(QtCore.QRect(9, 109, 124, 44))
        self.widget_left_direct.setObjectName("widget_left_direct")
        self.lineEdit_left_direct = QtWidgets.QLineEdit(self.widget_left_direct)
        self.lineEdit_left_direct.setGeometry(QtCore.QRect(60, 10, 51, 21))
        self.lineEdit_left_direct.setMinimumSize(QtCore.QSize(51, 21))
        self.lineEdit_left_direct.setMaximumSize(QtCore.QSize(51, 21))
        self.lineEdit_left_direct.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_left_direct.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_left_direct.setObjectName("lineEdit_left_direct")
        self.label_5 = QtWidgets.QLabel(self.widget_left_direct)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 43, 17))
        self.label_5.setMinimumSize(QtCore.QSize(43, 17))
        self.label_5.setMaximumSize(QtCore.QSize(43, 17))
        self.label_5.setObjectName("label_5")
        self.widget_right_direct = QtWidgets.QWidget(KeyConfig)
        self.widget_right_direct.setGeometry(QtCore.QRect(139, 109, 123, 44))
        self.widget_right_direct.setObjectName("widget_right_direct")
        self.lineEdit_right_direct = QtWidgets.QLineEdit(self.widget_right_direct)
        self.lineEdit_right_direct.setGeometry(QtCore.QRect(60, 10, 51, 21))
        self.lineEdit_right_direct.setMinimumSize(QtCore.QSize(51, 21))
        self.lineEdit_right_direct.setMaximumSize(QtCore.QSize(51, 21))
        self.lineEdit_right_direct.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_right_direct.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_right_direct.setObjectName("lineEdit_right_direct")
        self.label_6 = QtWidgets.QLabel(self.widget_right_direct)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 43, 17))
        self.label_6.setMinimumSize(QtCore.QSize(43, 17))
        self.label_6.setMaximumSize(QtCore.QSize(43, 17))
        self.label_6.setObjectName("label_6")
        self.widget_down = QtWidgets.QWidget(KeyConfig)
        self.widget_down.setGeometry(QtCore.QRect(9, 159, 124, 44))
        self.widget_down.setObjectName("widget_down")
        self.lineEdit_down = QtWidgets.QLineEdit(self.widget_down)
        self.lineEdit_down.setGeometry(QtCore.QRect(60, 10, 51, 21))
        self.lineEdit_down.setMinimumSize(QtCore.QSize(51, 21))
        self.lineEdit_down.setMaximumSize(QtCore.QSize(51, 21))
        self.lineEdit_down.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_down.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_down.setObjectName("lineEdit_down")
        self.label_7 = QtWidgets.QLabel(self.widget_down)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 43, 17))
        self.label_7.setMinimumSize(QtCore.QSize(43, 17))
        self.label_7.setMaximumSize(QtCore.QSize(43, 17))
        self.label_7.setObjectName("label_7")
        self.widget_bottom = QtWidgets.QWidget(KeyConfig)
        self.widget_bottom.setGeometry(QtCore.QRect(139, 159, 123, 44))
        self.widget_bottom.setObjectName("widget_bottom")
        self.lineEdit_bottom = QtWidgets.QLineEdit(self.widget_bottom)
        self.lineEdit_bottom.setGeometry(QtCore.QRect(60, 10, 51, 21))
        self.lineEdit_bottom.setMinimumSize(QtCore.QSize(51, 21))
        self.lineEdit_bottom.setMaximumSize(QtCore.QSize(51, 21))
        self.lineEdit_bottom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_bottom.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_bottom.setReadOnly(True)
        self.lineEdit_bottom.setObjectName("lineEdit_bottom")
        self.label_8 = QtWidgets.QLabel(self.widget_bottom)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 43, 17))
        self.label_8.setMinimumSize(QtCore.QSize(43, 17))
        self.label_8.setMaximumSize(QtCore.QSize(43, 17))
        self.label_8.setObjectName("label_8")
        self.widget_turn = QtWidgets.QWidget(KeyConfig)
        self.widget_turn.setGeometry(QtCore.QRect(9, 209, 124, 44))
        self.widget_turn.setObjectName("widget_turn")
        self.lineEdit_turn = QtWidgets.QLineEdit(self.widget_turn)
        self.lineEdit_turn.setGeometry(QtCore.QRect(60, 10, 51, 21))
        self.lineEdit_turn.setMinimumSize(QtCore.QSize(51, 21))
        self.lineEdit_turn.setMaximumSize(QtCore.QSize(51, 21))
        self.lineEdit_turn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_turn.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_turn.setObjectName("lineEdit_turn")
        self.label_9 = QtWidgets.QLabel(self.widget_turn)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 43, 17))
        self.label_9.setMinimumSize(QtCore.QSize(43, 17))
        self.label_9.setMaximumSize(QtCore.QSize(43, 17))
        self.label_9.setObjectName("label_9")
        self.widget_turn_anti = QtWidgets.QWidget(KeyConfig)
        self.widget_turn_anti.setGeometry(QtCore.QRect(139, 209, 123, 44))
        self.widget_turn_anti.setObjectName("widget_turn_anti")
        self.lineEdit_turn_anti = QtWidgets.QLineEdit(self.widget_turn_anti)
        self.lineEdit_turn_anti.setGeometry(QtCore.QRect(60, 10, 51, 21))
        self.lineEdit_turn_anti.setMinimumSize(QtCore.QSize(51, 21))
        self.lineEdit_turn_anti.setMaximumSize(QtCore.QSize(51, 21))
        self.lineEdit_turn_anti.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_turn_anti.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_turn_anti.setObjectName("lineEdit_turn_anti")
        self.label_10 = QtWidgets.QLabel(self.widget_turn_anti)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 43, 17))
        self.label_10.setMinimumSize(QtCore.QSize(43, 17))
        self.label_10.setMaximumSize(QtCore.QSize(43, 17))
        self.label_10.setObjectName("label_10")
        self.button_close = QtWidgets.QPushButton(KeyConfig)
        self.button_close.setGeometry(QtCore.QRect(40, 260, 71, 31))
        self.button_close.setObjectName("button_close")
        self.button_save = QtWidgets.QPushButton(KeyConfig)
        self.button_save.setGeometry(QtCore.QRect(160, 260, 71, 31))
        self.button_save.setObjectName("button_save")

        self.retranslateUi(KeyConfig)
        QtCore.QMetaObject.connectSlotsByName(KeyConfig)

    def retranslateUi(self, KeyConfig):
        _translate = QtCore.QCoreApplication.translate
        KeyConfig.setWindowTitle(_translate("KeyConfig", "Dialog"))
        self.lineEdit_left.setText(_translate("KeyConfig", "J"))
        self.label.setText(_translate("KeyConfig", "左移"))
        self.lineEdit_right.setText(_translate("KeyConfig", "L"))
        self.label_2.setText(_translate("KeyConfig", "右移"))
        self.lineEdit_left_3.setText(_translate("KeyConfig", "N"))
        self.label_3.setText(_translate("KeyConfig", "左3"))
        self.lineEdit_right_3.setText(_translate("KeyConfig", "I"))
        self.label_4.setText(_translate("KeyConfig", "右3"))
        self.lineEdit_left_direct.setText(_translate("KeyConfig", "U"))
        self.label_5.setText(_translate("KeyConfig", "左头"))
        self.lineEdit_right_direct.setText(_translate("KeyConfig", "O"))
        self.label_6.setText(_translate("KeyConfig", "右头"))
        self.lineEdit_down.setText(_translate("KeyConfig", "K"))
        self.label_7.setText(_translate("KeyConfig", "下落"))
        self.lineEdit_bottom.setText(_translate("KeyConfig", "space"))
        self.label_8.setText(_translate("KeyConfig", "到底"))
        self.lineEdit_turn.setText(_translate("KeyConfig", "S"))
        self.label_9.setText(_translate("KeyConfig", "转-顺"))
        self.lineEdit_turn_anti.setText(_translate("KeyConfig", "D"))
        self.label_10.setText(_translate("KeyConfig", "转-逆"))
        self.button_close.setText(_translate("KeyConfig", "关闭"))
        self.button_save.setText(_translate("KeyConfig", "保存"))

