# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1047, 664)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(530, 40, 475, 563))
        self.layoutWidget.setObjectName("layoutWidget")
        self.mainRightLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.mainRightLayout.setContentsMargins(0, 0, 0, 0)
        self.mainRightLayout.setSpacing(6)
        self.mainRightLayout.setObjectName("mainRightLayout")
        self.poolContianerWidget = QtWidgets.QWidget(self.layoutWidget)
        self.poolContianerWidget.setMinimumSize(QtCore.QSize(385, 561))
        self.poolContianerWidget.setObjectName("poolContianerWidget")
        self.blockPoolWidget = QtWidgets.QWidget(self.poolContianerWidget)
        self.blockPoolWidget.setGeometry(QtCore.QRect(121, 99, 264, 462))
        self.blockPoolWidget.setAutoFillBackground(False)
        self.blockPoolWidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.blockPoolWidget.setObjectName("blockPoolWidget")
        self.speedHintWidget = QtWidgets.QWidget(self.poolContianerWidget)
        self.speedHintWidget.setGeometry(QtCore.QRect(0, 0, 110, 88))
        self.speedHintWidget.setStyleSheet("background-color:black;")
        self.speedHintWidget.setObjectName("speedHintWidget")
        self.nextHintWidget = QtWidgets.QWidget(self.poolContianerWidget)
        self.nextHintWidget.setGeometry(QtCore.QRect(0, 99, 110, 88))
        self.nextHintWidget.setStyleSheet("background-color:black;")
        self.nextHintWidget.setObjectName("nextHintWidget")
        self.lastHintWidget = QtWidgets.QWidget(self.poolContianerWidget)
        self.lastHintWidget.setGeometry(QtCore.QRect(0, 198, 110, 88))
        self.lastHintWidget.setStyleSheet("background-color:black;")
        self.lastHintWidget.setObjectName("lastHintWidget")
        self.mainRightLayout.addWidget(self.poolContianerWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.startBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.startBtn.setMinimumSize(QtCore.QSize(80, 30))
        self.startBtn.setMaximumSize(QtCore.QSize(80, 40))
        self.startBtn.setSizeIncrement(QtCore.QSize(0, 0))
        self.startBtn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.startBtn.setObjectName("startBtn")
        self.verticalLayout.addWidget(self.startBtn)
        self.exitBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.exitBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.exitBtn.setMaximumSize(QtCore.QSize(80, 30))
        self.exitBtn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.exitBtn.setObjectName("exitBtn")
        self.verticalLayout.addWidget(self.exitBtn)
        self.mainRightLayout.addLayout(self.verticalLayout)
        self.stateWidget = QtWidgets.QWidget(self.centralwidget)
        self.stateWidget.setGeometry(QtCore.QRect(60, 40, 401, 221))
        self.stateWidget.setStyleSheet("background-color:black")
        self.stateWidget.setObjectName("stateWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1047, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionKey_Config = QtWidgets.QAction(MainWindow)
        self.actionKey_Config.setObjectName("actionKey_Config")
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionKey_Config)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        self.exitBtn.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tetris"))
        self.startBtn.setText(_translate("MainWindow", "开始"))
        self.exitBtn.setText(_translate("MainWindow", "退出"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuEdit.setTitle(_translate("MainWindow", "&Edit"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionKey_Config.setText(_translate("MainWindow", "&Key Config"))

